### PR TITLE
Add realistic 511 keV model fitting to extended source spectral fitting nb

### PR DESCRIPTION
**Pull request by fieldrog**
Add realistic 511 keV model fitting to extended source spectral fitting nb

### CODE REVIEW

**Comment by ckarwin** [comment]
Hi @fieldrog, Overall your additions look good, and I think things are working ok. I have a number of comments that I think need to be addressed before merging.  

Comment 1: For copying the files from wasabi, I don’t really understand why you are writing this as the sum of multiple strings. It seems unnecessarily complex, and it’s also much less direct. I also don’t think you need to print each copy command, because it just creates extra output that’s not really informative, as it’s just the command that’s being ran. I think it would be better to just use a simple single command, as it was previously. 

Comment 2: Please put any needed imports for Example 3 at the top of the notebook with the rest of them. No need to repeat the imports. 

Comment 3: I discussed with Israel, and I think for now we can put your new classes (SpecFromDat, Wide_Asymm_Gaussian_on_sphere) in cosipy/threeml/custom_functions.py. You can then import these into the notebook. Eventually, we’ll want to move these into Astromodels. 

Comment 4: Regarding the doc string for SpecFromDat: I don’t understand why the initial description is repeated after “latex :”. What is the point of this? It’s also not clear what format is needed for the .dat file. Additionally, I don’t see the .dat file that you used for your models. 

Comment 5: Regarding Wide_Asymm_Gaussian_on_sphere, it is not obvious how the eccentricity connects to the scale height. I guess the connection is b = a*sqrt(1 - e^2). Please comment on this in the notebook so it’s more clear. 

Comment 6: I think the notebook can be simplified by just using one of the models, say, the thin disk model. The point of the example notebook is just to exemplify the basic tools. 

Comment 7: 
When you define the lists for the source parameters, I think you can just multiply the whole list by the units, instead of defining the units for each element of the list. It’s much cleaner this way. For example, the following should be equivalent:
mu  =  [511*u.keV,511*u.keV,511*u.keV,511*u.keV]
mu =  [511, 511, 511, 511]*u.keV
e.g. mu[0] = mu[1] = 511 keV
In this case you could actually do 
mu = [511]*4*u.keV, 
since all the elements are the same. 

When you define the spatial model components, I believe the scale height relates to the eccentricity as b = a*sqrt(1 - e^2). 
For the thick disk, this gives:
b = (60 degree)*sqrt(1-0.9845684334^2) = 10.5 deg
This matches the input model. 
However, for the thin disk you have:
b = (60 degree)*sqrt(1-0.9994942541^2) = 1.9 deg
But it should be: a = 90 deg and scale height = 3 deg. 
Can you double check that you’re using the correct inputs?

Comment 8: 
I think you can remove the plot of the weights for example 3. I added it in my example to demonstrate how the weights work for the extended analysis, but in general I don’t think the plot is very helpful. 

Comment 9:
print (results_thick.optimized_model[model]) is a long output and a bit redundant. I don’t think it’s really needed. 

Comment 10: 
As we discussed a bit, there are multiple ways to do the fit. I kind of like the way you did it, where you free the normalization of each component. It’s interesting to see the results compared to what was injected. Another fit variation is to free the scale height. Here you might also want to do a simplified fit for the other parameters, maybe the normalization of the disk, and a single normalization for the bulge components. If that is working, then maybe you can have two different fit variations for example 3: the one you already have, and then one where you fit the scale height. If you add the fit of the scale height, then you can just keep it very brief in the notebook, i.e. just the essential steps. Alternatively, you could just use one example where you fit the scale height -- indeed that would make things simpler, and might be the best choice (if it's working ok). 

Comment 11: Example 3 can probably start with reading in the binned data, since the steps for creating the binned data are already shown in the first example. The only thing that’s really different is the source file. In general, we should try to keep the notebook as simple as possible (and as short as possible), so people don’t get lost in the fine details.

**Comment by fieldrog** [comment]
Hi @ckarwin, 

Thanks a lot for the careful review! 

Comment 1 - got rid of print. For me, it was helpful to have the path, because locally i could use it if i had already downloaded all the data from wasabi, i knew where to look for it. But, ok, not a big deal, i can change it. 

Comment 2 - done 

Comment 3 - done

Comment 4- ok, i got rid of the statement. About the .dat file, I thought it should go on wasabi, but for now i can just package it in this directory since it is small. 

Comment 5 - done, added a definition of eccentricity in the model and a note giving the explicit expression for the scale height, in the notebook. 

Comment 6 - done. Thin disk model only. 

Comment 7 - done, thanks. 

Comment 8 - weights plot is gone

Comment 9 - that print statement is gone

Comment 11 - done

**Comment by fieldrog** [comment]
more to follow...

**Comment by fieldrog** [comment]
for the fitting, i'm interested in your take on the best way to fit the scale height, since it's really not just the scale height we would want to change, but also the size a of the spatial model, right? At least, between the thin disk model and the thick disk model that we use, both a and b change, not just b. Is there a constraint on a relative to b?

**Comment by ckarwin** [comment]
@fieldrog You're right, in reality both a and b will be unknown, and they will need to be determined from the data. But these are things that can be tested as part of the data challenge. To keep things simple, for the example I would fix a at the injected value (90 degrees for the thin disk model). 

Please let me know when everything is updated and ready to be checked again.

**Comment by ckarwin** [comment]
Hi @fieldrog Is everything updated with your last commit, or is there still more to come? No rush, just wanted to check because I'm not sure.

**Comment by fieldrog** [comment]
All updated! 
I think I addressed all of the comments. Possible to revert the last commit to go back to fitting fluxes only

**Comment by fieldrog** [comment]
thanks for checking!

**Comment by ckarwin** [comment]
Great, thanks again! I'll take a look tomorrow.

**Comment by ckarwin** [comment]
Hi @fieldrog, some more comments:

comment 1:
You use the following for the source definition:
models = ["centralPoint","narrowBulge","broadBulge","disk"]
sigma  =  [2./2.335,2./2.335,2./2.335, 3./2.335]*u.keV
 = [0.8565, 0.8565, 0.8565, 1.285]*u.keV
However, the actual values are:
sigma = [0.85, 0.85, 0.85, 1.27]
Thus, none of the values actually match. Is there a reason for defining sigma as the ratio of two numbers? The sigma values in the model should match exactly the injected values.

comment 2: 
All your sources are centered at b, l = 0,0. However, the narrow Gaussian should be centered at b,l = -1.25, 359.75. This is true for both the line source and the orthopositronium. 

comment 3: 
Fixing comments 1 and 2 should improve the likelihood compared to what you get now. Please double check. Hopefully, the scale height might also match better with the injected value. 

comment 4:
All of the cells in the notebook are not evaluated, specifically, for the first two examples. I'm guessing you went through this at some point and cleared the output. Please make sure that all the cells have their outputs. 

comment 5:
As we discussed at the last cosipy meeting, the doc string formatting should follow the numpy documentation style. I also noticed that some of your methods in the new classes you defined don't have any documentation. Can you please update the style and document all the methods?

**Comment by ckarwin** [comment]
Hi @fieldrog I uploaded the binned data file that you sent to wasabi. It's with the other binned data files from the extended source example notebook: 
cosi-pipeline-public/COSI-SMEX/cosipy_tutorials/extended_source_spectral_fit_galactic_frame/combined_binned_data_thick_disk.hdf5

**Comment by hiyoneda** [comment]
Hi @fieldrog @ckarwin, Thank you for your work. From me, the notebook is basically really to be merged. I ran through the notebook (except for the file download parts) and did not get any errors. I put some comments. If you consider it reasonable, please reflect it on the notebook.

(quick works):
- Instantiating COSILike and performing fitting take time. It could be better to add %%time command in these cells and show expected times. 
- The notebook is using combined_binned_data_thin_disk.hdf5, but I could not find in the wasabi. Instead, I found combined_binned_data_thick_disk.hdf5
- The parameter mu in the first example should be fixed because there is only one energy bin and cannot determine the width in principle. (I am wondering why threeML provides the best value with its error.)

(maybe after DC2)
- Now the asymmetric gaussian (used for the disk component) is parameterized with the major axis and eccentricity. I think that it is also useful to determine the major/minor axes for parameters so that we can directly see the result of the scale height.
- The class ModelMap for the deconvolution can generate the datacube as follows. Maybe it is useful when checking the results. This example shows the all sky image of the best-fitting disk component. If you have time, please try it.
```
import healpy as hp
from cosipy.image_deconvolution import ModelMap

model_map = ModelMap(nside = 32, energy_edges = np.array([509.,  513.]) * u.keV)
model_map.set_values_from_extendedmodel(results.optimized_model['disk'])

hp.mollview(model_map[:,0], norm = 'linear')
```

**Comment by hiyoneda** [comment]
I share the fitting result with the thick disk simulation dataset by thawing the major axis. Its initial value is 90 degrees.
The result seems fine, but the best-fit value (53.3 \pm 0.5 deg.) is smaller than the truth value (60 deg). It could be improved when Comments are solved, but in the near future, it would be good if we check more (is the error underestimated? is the response correct? etc.)

Screenshot 2024-01-18 at 18 49 33

**Comment by fieldrog** [comment]
@ckarwin I shared google drive links for both the binned data for both thin and thick disk. Did you see both of them? Per Hiroki's comment

**Comment by fieldrog** [comment]
Thanks, Hiroki!

> Hi @fieldrog @ckarwin, Thank you for your work. From me, the notebook is basically really to be merged. I ran through the notebook (except for the file download parts) and did not get any errors. I put some comments. If you consider it reasonable, please reflect it on the notebook.
> 
> (quick works):
> 
>     * Instantiating COSILike and performing fitting take time. It could be better to add %%time command in these cells and show expected times.

Will do! 
> 
>     * The notebook is using combined_binned_data_thin_disk.hdf5, but I could not find in the wasabi. Instead, I found combined_binned_data_thick_disk.hdf5

@ckarwin did you see the link i sent for both think and thick disk combined files? 
> 
>     * The parameter mu in the first example should be fixed because there is only one energy bin and cannot determine the width in principle. (I am wondering why threeML provides the best value with its error.)

@ckarwin i'll leave this one for you, since you wrote that section of the notebook, unless you prefer me to fix it now
> 
> 
> (maybe after DC2)
> 
>     * Now the asymmetric gaussian (used for the disk component) is parameterized with the major axis and eccentricity. I think that it is also useful to determine the major/minor axes for parameters so that we can directly see the result of the scale height.
> 
>     * The class ModelMap for the deconvolution can generate the datacube as follows. Maybe it is useful when checking the results. This example shows the all sky image of the best-fitting disk component. If you have time, please try it.
> 
> 
> ```
> import healpy as hp
> from cosipy.image_deconvolution import ModelMap
> 
> model_map = ModelMap(nside = 32, energy_edges = np.array([509.,  513.]) * u.keV)
> model_map.set_values_from_extendedmodel(results.optimized_model['disk'])
> 
> hp.mollview(model_map[:,0], norm = 'linear')
> ```

**Comment by fieldrog** [comment]
> Hi @fieldrog I uploaded the binned data file that you sent to wasabi. It's with the other binned data files from the extended source example notebook: cosi-pipeline-public/COSI-SMEX/cosipy_tutorials/extended_source_spectral_fit_galactic_frame/combined_binned_data_thick_disk.hdf5

thanks! did you see the other link i sent for the thin disk?

**Comment by fieldrog** [comment]
Hi @ckarwin, thanks for the comments! Responses inline below: 

> Hi @fieldrog, some more comments:
> 
> comment 1: You use the following for the source definition: models = ["centralPoint","narrowBulge","broadBulge","disk"] sigma = [2./2.335,2./2.335,2./2.335, 3./2.335]*u.keV = [0.8565, 0.8565, 0.8565, 1.285]*u.keV However, the actual values are: sigma = [0.85, 0.85, 0.85, 1.27] Thus, none of the values actually match. Is there a reason for defining sigma as the ratio of two numbers? The sigma values in the model should match exactly the injected values.

Yes, i was following the description from Carolyn  somewhere that we were looking at 2 keV and 3keV FWHM values for these two lines. With the values defined this way, it is easy to see that we are looking at lines with 2 and 3 keV fwhm as per the description. I can change to a decimal to match exactly the injected numbers.  
> 
> comment 2: All your sources are centered at b, l = 0,0. However, the narrow Gaussian should be centered at b,l = -1.25, 359.75. This is true for both the line source and the orthopositronium.

Noted, thanks for catching that! 
> 
> comment 3: Fixing comments 1 and 2 should improve the likelihood compared to what you get now. Please double check. Hopefully, the scale height might also match better with the injected value.

Will do
> 
> comment 4: All of the cells in the notebook are not evaluated, specifically, for the first two examples. I'm guessing you went through this at some point and cleared the output. Please make sure that all the cells have their outputs.

Will do
> 
> comment 5: As we discussed at the last cosipy meeting, the doc string formatting should follow the numpy documentation style. I also noticed that some of your methods in the new classes you defined don't have any documentation. Can you please update the style and document all the methods?

clarification, this is only for the new classes, right? Don't need to update all comments throughout the notebooks?

**Comment by ckarwin** [comment]
Hi @fieldrog,

> thanks! did you see the other link i sent for the thin disk?

No, I didn't. Maybe can you resend it?

> @ckarwin i'll leave this one for you, since you wrote that section of the notebook, unless you prefer me to fix it now

That's fine.

> clarification, this is only for the new classes, right? Don't need to update all comments throughout the notebooks?

That's right, just for the actual source code (that you wrote) of the classes, not the notebooks.

**Comment by ckarwin** [comment]
The binned thin disk data is on wasabi now: https://s3.us-west-1.wasabisys.com/cosi-pipeline-public/COSI-SMEX/cosipy_tutorials/extended_source_spectral_fit_galactic_frame/combined_binned_data_thin_disk.hdf5

**Comment by ckarwin** [comment]
Thanks @fieldrog and @hiyoneda for your work on this! I'm going to merge into my main, and we'll merge into cosipy main very soon (I just need to double check a couple things first).

**Review by ckarwin — COMMENTED** [review]
Everything is ok. Merged.

**Pull request merged**
